# Jetson Orin series
source "${LDK_DIR}/jetson-orin-nano-devkit-nvme.conf";

EMC_OPT_DISABLE_FUSE_OVERRIDE=0
PINMUX_CONFIG="Orin-tek-orin-a1-pinmux.dtsi";
OVERLAY_DTB_FILE+=",tegra234-dcb-p3767-0000-hdmi.dtbo";
DCE_OVERLAY_DTB_FILE="tegra234-dcb-p3767-0000-hdmi.dtbo";

# TARGET support
FILE=$(basename $BASH_SOURCE)
NAME=${FILE%.conf}
TN_BOARD=$(echo $NAME | awk -F- '{print $1"-"$2}')
SOM=$(echo $NAME | awk -F- '{print $3"-"$4}')

if [[ "${SOM}" == *"orin-nx"* ]]; then
    DTB_FILE="tegra234-tek-orin+p3767-0000-nv.dtb";
    BOARDID="3767"
    BOARDSKU="0000"
    FAB="300"
    BOARDREV="L.2"
    CHIP_SKU="00:00:00:D3"
    RAMCODE_ID="0"
elif [[ "${SOM}" == *"orin-nano"* ]]; then
    DTB_FILE="tegra234-tek-orin+p3767-0003-nv.dtb";
    BOARDID="3767"
    BOARDSKU="0003"
    FAB="300"
    BOARDREV="N.1"
    CHIP_SKU="00:00:00:D5"
    RAMCODE_ID="2"
else
    echo "Invalid board name!";
    exit 1;
fi

if [[ "${TN_BOARD}" == *"tek6"* ]]; then
    OVERLAY_DTB_FILE+=",tegra234-p3767-camera-tek-orin-vls3.dtbo";
fi

TBCDTB_FILE="${DTB_FILE}";

#echo "Board info=$BOARDID-$BOARDSKU-$FAB-$BOARDREV CHIP_SKU=${CHIP_SKU} RAMCODE=$RAMCODE_ID"
